.\"                                      Hey, EMACS: -*- nroff -*-
.\" First parameter, NAME, should be all caps
.\" Second parameter, SECTION, should be 1-8, maybe w/ subsection
.\" other parameters are allowed: see man(7), man(1)
.TH fillets 6 "July  8, 2004"
.\" Please adjust this date whenever revising the manpage.
.\"
.\" Some roff macros, for reference:
.\" .nh        disable hyphenation
.\" .hy        enable hyphenation
.\" .ad l      left justify
.\" .ad b      justify to both left and right margins
.\" .nf        disable filling
.\" .fi        enable filling
.\" .br        insert line break
.\" .sp <n>    insert n+1 empty lines
.\" for manpage-specific macros, see man(7)
.SH NAME
fillets \- puzzle game about witty fish saving the world sokoban style
.SH SYNOPSIS
.B fillets
.RI [ options ]
.br
.SH DESCRIPTION
This manual page was written for the Debian distribution
because the original program does not have a manual page.
.PP
.\" TeX users may be more comfortable with the \fB<whatever>\fP and
.\" \fI<whatever>\fP escape sequences to invode bold face and italics, 
.\" respectively.
\fBFish Fillets \fPis strictly a puzzle game. The goal in every of the seventy
levels is always the same: find a safe way out. The fish utter witty remarks
about their surroundings, the various inhabitants of their underwater realm
quarrel among themselves or comment on the efforts of your fish. The whole
game is accompanied by quiet, comforting music.
.br
.br
There is an excellent in game tutorial available, so you can start
playing right away.
.br
.br
So far the commandline options are undocumented. This is a known bug.
.\"OPTIONS
.\".TP
.\".B \-h, \-\-help
.\"Show summary of options.
.\".TP
.\".B \-v, \-\-version
.\"Show version of program.
.SH SEE ALSO
.BR /usr/share/doc/fillets-ng/manual.html
.br
.SH AUTHOR
This manual page was written by fabian linzberger <e@lefant.net>,
for the Debian project (but may be used by others).
