.\"                                      Hey, EMACS: -*- nroff -*-
.\" First parameter, NAME, should be all caps
.\" Second parameter, SECTION, should be 1-8, maybe w/ subsection
.\" other parameters are allowed: see man(7), man(1)
.TH fillets 6 "April 18, 2005"
.\" Please adjust this date whenever revising the manpage.
.\"
.\" Some roff macros, for reference:
.\" .nh        disable hyphenation
.\" .hy        enable hyphenation
.\" .ad l      left justify
.\" .ad b      justify to both left and right margins
.\" .nf        disable filling
.\" .fi        enable filling
.\" .br        insert line break
.\" .sp <n>    insert n+1 empty lines
.\" for manpage-specific macros, see man(7)
.SH NAME
fillets \- puzzle game about witty fish saving the world sokoban style
.SH SYNOPSIS
.B fillets
.RI [ options ]
.br
.SH DESCRIPTION
.PP
\fBFish Fillets \fPis strictly a puzzle game. The goal in every of the seventy
levels is always the same: find a safe way out. The fish utter witty remarks
about their surroundings, the various inhabitants of their underwater realm
quarrel among themselves or comment on the efforts of your fish. The whole
game is accompanied by quiet, comforting music.
.PP
There is an excellent in game tutorial available, so you can start
playing right away.
.PP
.SH OPTIONS
.TP
.B \-h, \-\-help
Show summary of options.
.TP
.B \-v, \-\-version
Show version of program.
.TP
.B \-c, \-\-config
Show config variables and values.
.TP
.B fullscreen=<boolean>
Turn fullscreen on/off.
.br
Default: fullscreen=0
.TP
.B lang=<code>
ISO 639 2-letter code (for ex.: en, cs, fr, de)
.br
see http://www.w3.org/WAI/ER/IG/ert/iso639.htm
.br
Default: lang=LC_MESSAGES
.TP
.B loglevel=<number>
Loglevel uses same numbers as syslog.
.br
for ex.: 3 for ERROR, 4 for WARNING, 6 for INFO, 7 for DEBUG
.br
Default: loglevel=6
.TP
.B show_steps=<boolean>
Show step counter in level.
.br
Default: show_steps=0
.TP
.B sound=<boolean>
Turn sound on/off.
.br
Default: sound=1
.TP
.B speech=<code>
ISO 639 2-letter code (for ex.: en, cs, fr, de)
.br
see http://www.w3.org/WAI/ER/IG/ert/iso639.htm
.br
Default: same as lang
.TP
.B subtitles=<boolean>
Show subtitles in level.
.br
Default: subtitles=1
.TP
.B systemdir=<path>
Path to game data.
.TP
.B userdir=<path>
Path to game data.
.br
Default: userdir=$HOME/.fillets-ng
.TP
.B volume_sound=<number>
Sound volume in percentage.
.br
Default: volume_sound=90
.TP
.B volume_music=<number>
Music volume in percentage.
.br
Default: volume_music=50
.TP
.B worldmap=<path>
Relative path to worldmap file.
.br
Useful for external levels.
.br
Default: worldmap=script/worldmap.lua

.PP
.SH USAGE
Up, down, left and right arrow keys control the current fish.
.br
Use space bar to switch between the fish.
.PP
restart level - Backspace
.br
undo - -
.br
help - F1
.br
save game - F2
.br
load game - F3
.br
show/hide level move counter - F5
.br
show/hide subtitles - F6
.br
game menu - F10
.br
toggle fullscreen - F11
.br
increase game speed - hold down Shift
.PP
Find more information in the "How to Play" html manual listed below.
.PP
.SH SEE ALSO
.BR /usr/share/doc/fillets-ng/html/manual.html
.br
.BR http://fillets.sf.net 
.br
.SH AUTHORS
.PP
Fish Fillets - Next Generation was written by
.PP
Ivo Danihelka <ivo@danihelka.net>
.br
- main developer
.br
- developed new game engine
.PP
Pavel Danihelka <fillets@danihelka.net>
.br
- webmaster, level data, documentation
.PP
Frederic Panico <fratloev@yahoo.fr>
.br
- French translation
.PP
Ronny Standtke <Ronny.Standtke@gmx.de>
.br
- German translation
.PP
Simone Cociancich <simone.coch@tin.it>
.br
- Italian translation
.PP
Przemek Bojczuk <przemek@bojczuk.pl>
.br
- Polish translation
.PP
César Catrián C. <ccatrian@eml.cc>
.br
- Spanish translation
.PP
Astrid de Wijn <a.s.dewijn@phys.uu.nl>
.br
- Dutch translation
.PP
Damyan Ivanov <divanov@creditreform.bg>
.br
- Bulgarian translation
.PP
Olov Gustavsson <olov.gustavsson@bredband.net>
.br
- Swedish translation
.PP
Marko Burjek <email4marko[at]gmail[dot]com>
.br
- Slovenian translation
.PP
Ricardo Faria <rickybrag@gmail.com>
.br
- Brazilian Portuguese translation
.PP
Leonid Myravjev <lemy@bk.ru>
.br
- Russian translation
.PP
ALTAR interactive <info@altarinteractive.com>
.br
- developed original game in 1998 (for Win32)
.br
- released code and data under GNU/GPL in 03/2004
.PP
This manual page was written for the Debian distribution
because the original program did not have a manual page.
.PP
This manual page was written by fabian linzberger <e@lefant.net>,
for the Debian project (but may be used by others).
